### ISSUE TITLE
Method 'ReadNodeInfo' ... does not have an implementation

### ISSUE THREAD

**Issue by ryanmckenzie-rsm** [KN4CK3R/ReClass.NET-SamplePlugin#2]
I built the example plugin and ReClass throws this exception:
`Method 'ReadNodeInfo' in type 'SamplePluginManaged.SampleNodeInfoReader' from assembly 'SamplePluginManaged, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation. (SamplePluginManaged)
`

**Comment by KN4CK3R** [comment]
Did you use the plugin with the ReClass.NET version from the release page? It will only work if you build ReClass.NET too because the sample plugin code is synched to the current ReClass.NET code.

**Comment by ryanmckenzie-rsm** [comment]
Yes I did
